id: P005458
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W23191
  title: འདས་ལོག་གསུམ་གྱི་ལོ་རྒྱུས
  author: ''
  volumes:
    37d66888dec843bc858136d32a9a6539:
      image_group_id: I0531
      title: ''
      volume_number: 1
      total_pages: 543
      base_file: v001.txt
