id: I50A96404
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T23:52:39+00:00'
last_modified: '2022-06-08T03:13:42.488056+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23191
  title: འདས་ལོག་གསུམ་གྱི་ལོ་རྒྱུས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C7B3:
      image_group_id: I0531
      title: ''
      total_pages: 543
      order: 1
      base_file: C7B3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
